
defaults:
  - env: local
  - solution: dummy_solution

  # disable logging by Hydra
  - override hydra/job_logging: none
  - override hydra/hydra_logging: none
  - _self_

hydra:
  run:
      dir: ${env.artifacts_path}

solution:
  do_train: false
  do_predict : false
  do_create_submission: false

wandb:
  enabled: false
  project: kaggle_ell

git_hash: none